plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80
  Exclude:
    - "*.gemspec"

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "lib/tty/markdown/converter.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 5

Naming/FileName:
  Exclude:
    - "lib/tty-markdown.rb"

RSpec/DescribedClass:
  Exclude:
    - "spec/perf/**/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
