---
name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "bin/**"
      - "examples/**"
      - "*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "bin/**"
      - "examples/**"
      - "*.md"
jobs:
  tests:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "2.0"
          - "2.1"
          - "2.2"
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "3.0"
          - "3.1"
          - ruby-head
          - jruby-9.2
          - jruby-9.3
          - jruby-9.4
          - jruby-head
          - truffleruby-head
        include:
          - ruby: "2.7"
            os: ubuntu-latest
            coverage: true
    env:
      COVERAGE: ${{ matrix.coverage }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake ci
